Caffein/Map/urls.py
from django.urls import path
from Map.views import map_view
from django.conf.urls.static import static
from django.conf import settings

app_name:'Map'
urlpatterns=[
    path('',map_view, name='map'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Caffein/store/urls.py
from django.urls import path
from .views import index,StoreList,StoreDetail,like_toggle,search,StoreUpdate,update_menu
from django.conf.urls.static import static
from django.conf import settings
urlpatterns=[
    path('detail/<int:pk>',StoreDetail.as_view(), name='store_detail'),
    path('update/<int:pk>',StoreUpdate.as_view(), name='store_update'),
    path('update_menu/<int:store_id>/<int:menu_id>',update_menu,name="update_menu"),
    path("list/",StoreList.as_view(), name="store_list"),
    path("like_toggle/<int:store_id>",like_toggle,name='like_toggle'),
    path('search/',search,name="search"),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Caffein/store/models.py
from django.db import models
from django.conf import settings

# Create your models here.
#카페 스토리, 컨텐츠 요소 #카페 인스타 스토리, 카페 아이콘
#전화번호 #위치 # 약도 #운영시간 #특징(단체석, 와이파이) #SNS #메뉴 #리뷰 #사진


class Store(models.Model):
    # host = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    x = models.FloatField('경도')
    y = models.FloatField('위도')
    image = models.ImageField('대표이미지',blank=True)
    like_count = models.PositiveIntegerField(default=0)

    name = models.CharField('이름',max_length=200)
    address = models.TextField('주소',blank=True)
    phone_number = models.CharField('전화번호', max_length=20,blank=True)
    sns = models.TextField('SNS',blank=True)
    open_time = models.TextField("운영시간",blank=True)

    Info = models.TextField("카페이야기",blank=True)
    story = models.FileField("스토리",upload_to="store/story",blank=True)
    icon = models.ImageField("아이콘",upload_to="store/icon",blank=True)
    more_info = models.TextField("세부정보",blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = '카페'

    def __str__(self):
        return self.name

class Menu(models.Model):
    class Meta:
        verbose_name_plural = '메뉴'

    store = models.ForeignKey(Store,on_delete=models.SET_NULL, null=True)
    store_menu = models.TextField("가게메뉴",blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.store_menu

class Review(models.Model):
    class Meta:
        verbose_name_plural = '리뷰'

    store = models.ForeignKey(Store,on_delete=models.SET_NULL,null=True)
    user_review = models.TextField("리뷰",blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class StorePic(models.Model):
    class Meta:
        verbose_name_plural = '사진'
    store = models.ForeignKey(Store,on_delete=models.SET_NULL,null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Tag(models.Model):
    class Meta:
        verbose_name_plural = '태그들'
    #나중에 manyto many로 연결해주자
    # created_at = models.DateTimeField(auto_now_add=True)
    # updated_at = models.DateTimeField(auto_now=True)
    pass

Caffein/store/forms.py
from django import forms
from .models import Menu


class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ('store_menu',)

Caffein/store/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy
from .models import Store,Menu
from user.models import CaffeInUser
from django.shortcuts import render, redirect,HttpResponseRedirect
from .forms import MenuForm
# Create your views here.

class StoreList(ListView):
    model = Store
    context_object_name = 'all_store'
    template_name = 'store_list.html'

class StoreDetail(DetailView):
    model = Store
    context_object_name = 'one_store'
    template_name = 'store_detail.html'


class StoreUpdate(UpdateView):
    model = Store
    fields = ('image','name','address','open_time','Info','more_info')
    context_object_name = 'one_store'
    template_name = 'store_update.html'
  

    def get_success_url(self):
        detail_id=self.kwargs['pk']
        return reverse_lazy('store_detail', kwargs={'pk': detail_id})





@login_required(login_url='login')
def like_toggle(request, store_id):
    user = request.user
    store = Store.objects.get(id=store_id)

    try:
        check = user.likes.all().get(id=store_id)
        user.likes.remove(store_id)
        store.like_count -= 1
        store.save()
    except:
        user.likes.add(store_id)
        store.like_count += 1
        store.save()
    
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def index(request):
    
    return render(request,"store_detail.html")

def search(request):
    context=dict()
    store_list = Store.objects.all()
    store = request.POST.get('search',"")

    if store:
        store_list = store_list.filter(name__icontains=store)
        context['store_list'] = store_list
        context['search'] = search
        return render(request,'search.html',context)
    else:
        return render(request,'search.html')


def update_menu(request,store_id,menu_id):
    context = dict()
    
    one_store = Store.objects.get(pk=store_id)
    context['one_store'] = one_store

    my_menu = Menu.objects.get(id=menu_id)

    menu_form = MenuForm(instance=my_menu)
    context['menu_form'] = menu_form

    if request.method=="POST":
        update_form =  MenuForm(request.POST,instance=my_menu)
        if update_form.is_valid():
            update_form.save()
            return redirect('store_detail',store_id)

  
    return render(request,'menu_update.html',context)


# def search(request):
#     context=dict()
#     store_list = Store.objects.all()
#     store = request.POST.get('search',"")

#     if store:
#         store_list = store_list.filter(name__icontains=store)
#         context['store_list'] = store_list
#         context['search'] = search
#         return render(request,'search.html',context)
#     else:
#         return render(request,'search.html')


# class PublisherDetail(DetailView):
    # queryset = Publisher.objects.all()

#     model = Publisher

#     def get_context_data(self, **kwargs):
#         # Call the base implementation first to get a context
#         context = super().get_context_data(**kwargs)
#         # Add in a QuerySet of all the books
#         context['book_list'] = Book.objects.all()
#         return context

Caffein/store/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Store detail views</h1>
  </body>
</html>

Caffein/store/templates/menu_update.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/cafe.css' %}" />
    <link rel="stylesheet" href="{% static 'css/cafe_update.css'%}">
  </head>
  <body>
    <div class="container cafelist">
      <header class="detail_header">
       <img src="{{one_store.image.url}}">
        <div class="detail_header_info_wapper">
          <div class="cafe_card_story">
            <img src="{{one_store.icon.url}}">
          </div>
          <div class="cafe_card_title">{{one_store}}</div>
         
        </div>
      </header>
      <div class="detail_title">INFORMATION</div>
      <div class="detail_info_wrapper">
        <div class="detail_info_row">
          <div class="detail_info_icon">
            <img class="icon-image" src="/static/지도 하양.png" >
          </div>
          <p class="detail_info_text">
            {{one_store.address}}<br />
            <span class="detail_info_subtext">{{one_store.open_time}}</span>
          </p>
        </div>
        <div class="detail_info_row">
          <div class="detail_info_icon">
            <img class="icon-image" src="/static/메뉴 하양.png" >
          </div>
          <p class="detail_info_text">"{{one_store.Info}}"</p>
        </div>
        <div class="detail_info_row">
          <div class="detail_info_icon">
            <img class="icon-image" src="/static/메뉴판 하양.png" >
          </div>
          <div class="menu">Popular Menu
                <form method="POST">
        {% csrf_token %}
        {%for i in menu_form%}
        {% if i.name == "가게 메뉴" %}
        <div class="menu-text"></div>
        
        {%endif%}
        {{i}}
        {%endfor%}
        <input id="menu-update" type="submit" value="수정">
        </form>
        </div>
    </div>
       
        <div class="detail_info_row">
          <div class="detail_info_icon">
            <img class="icon-image-mark" src="/static/북마크 하양.png" >
          </div>
          <p class="detail_info_text">{{one_store.more_info}}</p>
        </div>
      
      

     

      <div class="detail_story_wrapper">
        <p>STORY</p>
        <div class="detail_story_item">
          <img
            src="https://search.pstatic.net/common/?autoRotate=true&quality=95&type=w750&src=http%3A%2F%2Fblogfiles.naver.net%2FMjAxODA1MTFfMjU4%2FMDAxNTI2MDE3MjY1Nzgy.-vMu-iXbewOfkRSBs5W2Os9tgxcGt6HQbwyLSNS5_ncg.PUklUIOszp1xykNX6rZkYkOXJJ8-pbuv38QK0DZrbCsg.JPEG.always918%2FIMG_4021.jpg"
          />
        </div>
        <div class="detail_story_item">
          <img
            src="https://search.pstatic.net/common/?autoRotate=true&quality=95&type=w750&src=http%3A%2F%2Fblogfiles.naver.net%2FMjAxODA1MTFfMjU4%2FMDAxNTI2MDE3MjY1Nzgy.-vMu-iXbewOfkRSBs5W2Os9tgxcGt6HQbwyLSNS5_ncg.PUklUIOszp1xykNX6rZkYkOXJJ8-pbuv38QK0DZrbCsg.JPEG.always918%2FIMG_4021.jpg"
          />
        </div>
        <div class="detail_story_item">
          <img
            src="https://search.pstatic.net/common/?autoRotate=true&quality=95&type=w750&src=http%3A%2F%2Fblogfiles.naver.net%2FMjAxODA1MTFfMjU4%2FMDAxNTI2MDE3MjY1Nzgy.-vMu-iXbewOfkRSBs5W2Os9tgxcGt6HQbwyLSNS5_ncg.PUklUIOszp1xykNX6rZkYkOXJJ8-pbuv38QK0DZrbCsg.JPEG.always918%2FIMG_4021.jpg"
          />
        </div>
      </div>
    </div>


    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous">
    </script>
    <script>
      $('.arrow').click(function(){
        $('.detail_info_menu').slideToggle();
      });

    </script>
  </body>
</html>

Caffein/store/templates/search.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>검색 페이지</title>
  <link rel="stylesheet" href="{% static 'css/cafe.css' %}" />
</head>

<body>
  <div id="nav">
    <a href="{% url 'map' %}">

      <image src="/static/map.png" class="mapbtn"></image>

    </a>
    <a href="{% url 'store_list' %}">

      <image src="/static/list.png"></image>

    </a>
    {% if user.is_authenticated %}
    <a href="{% url 'mypage' %}">


      <image src="/static/user2.png" class="userbtn"></image>

    </a>
    {% else %}
    <a href="{% url 'login' %}">


      <image src="/static/user2.png" class="userbtn"></image>

    </a>
    {% endif %}
  </div>

  <form method="POST">
    {%csrf_token%}
    {% if not store_list %}
    <div class="container cafelist">
      <form method="POST" action="{% url 'search' %}">
        {%csrf_token%}
        <div class="search">
          <div class="search-bar-wrapper">
            <input type="text" id="search-bar" placeholder="카페를 검색해주세요" name="search" value="{{search}}">
            <input type="image" src="{% static 'search.png'%}" id="search-btn"></image>

          </div>
        </div>
        <p class="p">검색 결과가 없습니다😂😂
          <br>다시 검색해주세요👀👀</p>
    </div>
  </form>


  {% else %}

  <div class="container cafelist">
    <form method="POST" action="{% url 'search' %}">
      {%csrf_token%}
      <div class="search">
        <div class="search-bar-wrapper">
          <input type="text" id="search-bar" placeholder="카페를 검색해주세요" name="search" value="{{search}}">
          <input type="image" src="{% static 'search.png'%}" id="search-btn"></image>

        </div>
      </div>
    </form>
    <div class="cafe_card_wrapper">
      <div class="cafe_card_filter">
        <span>거리순 |</span>
        <span>관심순 |</span>

        <span>소식순</span>
      </div>
      {% for i in store_list.all %}

      <a href="{% url 'store_detail' i.id%}">
        <div class="cafe_card_img">
          <img src='{{i.image.url}}'>
        </div>
        <div class="cafe_card_content_wrap">
          <!-- <div class="cafe_card_story">
            <img src='{{i.story}}'>
          </div> -->
          <div class="cafe_card_content">
            <div class="cafe_card_title">{{i}}</div>
            <div class="cafe_card_loc">📌{{i.address}}<br>
            </div>

            <div class="cafe_card_time">⏰{{i.open_time}}<br>
            </div>
          </div>
          <div class="cafe_card_like">
            <a href="{% url 'like_toggle' i.id %}">
              {% if i in user.likes.all %}
              X:{{i.like_count}}
              {% else %}
              ♡:{{i.like_count}}
              {% endif %}
            </a>
          </div>
        </div>
      </a>
      {% endfor %}
      {% endif %}



</body>

</html>

Caffein/store/templates/store_detail.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/cafe.css' %}" />
  </head>
  <body>
    <div class="container cafelist">
      <header class="detail_header">
       <img src="{{one_store.image.url}}">
        <div class="detail_header_info_wapper">
          <div class="cafe_card_story">
            <img src="{{one_store.icon.url}}">
          </div>
          <div class="cafe_card_title">{{one_store}}</div>
          <div class="cafe_card_like">
            <a id="like_toggle" href="{% url 'like_toggle' one_store.id %}">
              {% if one_store in user.likes.all %}
              ♥ {{one_store.like_count}}
              {% else %}
              ♡ {{one_store.like_count}}
              {% endif %}
            </a>
          </div>
        </div>

        <div class="edit_cafe_detail">
           <a id = "edit" href="{% url 'store_update' one_store.id %}">edit</a>
        </div>
      </header>
      <div class="detail_title">INFORMATION</div>
      <div class="detail_info_wrapper">
        <div class="detail_info_row">
          <div class="detail_info_icon">
            <img class="icon-image" src="/static/지도 하양.png" >
          </div>
          <p class="detail_info_text">
            {{one_store.address}}<br />
            <span class="detail_info_subtext">{{one_store.open_time}}</span>
          </p>
        </div>
        <div class="detail_info_row">
          <div class="detail_info_icon">
            <img class="icon-image" src="/static/메뉴 하양.png" >
          </div>
          <p class="detail_info_text">"{{one_store.Info}}"</p>
        </div>
        <div class="detail_info_row">
          <div class="detail_info_icon">
            <img class="icon-image" src="/static/메뉴판 하양.png" >
          </div>
          <div class="menu">Popular Menu
            <img class="arrow" src="/static/arrow.png" >
          </div>
          
        </div>
        <div class="detail_info_menu">
        {%for menu in one_store.menu_set.all %}
        <div class="one_menu">
          {{menu.store_menu }}
        </div>
        {% endfor %}
        </div>
        <div class="detail_info_row">
          <div class="detail_info_icon">
            <img class="icon-image-mark" src="/static/북마크 하양.png" >
          </div>
          <p class="detail_info_text">{{one_store.more_info}}</p>
        </div>
      </div>

     

      <div class="detail_story_wrapper">
        <p>STORY</p>
        <div class="detail_story_item">
          <img
            src="https://search.pstatic.net/common/?autoRotate=true&quality=95&type=w750&src=http%3A%2F%2Fblogfiles.naver.net%2FMjAxODA1MTFfMjU4%2FMDAxNTI2MDE3MjY1Nzgy.-vMu-iXbewOfkRSBs5W2Os9tgxcGt6HQbwyLSNS5_ncg.PUklUIOszp1xykNX6rZkYkOXJJ8-pbuv38QK0DZrbCsg.JPEG.always918%2FIMG_4021.jpg"
          />
        </div>
        <div class="detail_story_item">
          <img
            src="https://search.pstatic.net/common/?autoRotate=true&quality=95&type=w750&src=http%3A%2F%2Fblogfiles.naver.net%2FMjAxODA1MTFfMjU4%2FMDAxNTI2MDE3MjY1Nzgy.-vMu-iXbewOfkRSBs5W2Os9tgxcGt6HQbwyLSNS5_ncg.PUklUIOszp1xykNX6rZkYkOXJJ8-pbuv38QK0DZrbCsg.JPEG.always918%2FIMG_4021.jpg"
          />
        </div>
        <div class="detail_story_item">
          <img
            src="https://search.pstatic.net/common/?autoRotate=true&quality=95&type=w750&src=http%3A%2F%2Fblogfiles.naver.net%2FMjAxODA1MTFfMjU4%2FMDAxNTI2MDE3MjY1Nzgy.-vMu-iXbewOfkRSBs5W2Os9tgxcGt6HQbwyLSNS5_ncg.PUklUIOszp1xykNX6rZkYkOXJJ8-pbuv38QK0DZrbCsg.JPEG.always918%2FIMG_4021.jpg"
          />
        </div>
      </div>
    </div>


    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous">
    </script>
    <script>
      $('.arrow').click(function(){
        $('.detail_info_menu').slideToggle();
      });

    </script>
  </body>
</html>

Caffein/store/templates/store_list.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'css/cafe.css' %}" />
</head>

<body>
  <div class="container cafelist">

    <header>
      <div id="nav">
        <a href="{% url 'map' %}">

          <image src="/static/map.png" class="mapbtn"></image>

        </a>
        <a href="{% url 'store_list' %}">

          <image src="/static/list.png"></image>

        </a>
        {% if user.is_authenticated %}
        <a href="{% url 'mypage' %}">


          <image src="/static/user2.png" class="userbtn"></image>

        </a>
        {% else %}
        <a href="{% url 'login' %}">


          <image src="/static/user2.png" class="userbtn"></image>

        </a>
        {% endif %}
      </div>
    </header>
    <form method="POST" action="{% url 'search' %}">
      {%csrf_token%}
      <div class="search">
        <div class="search-bar-wrapper">
          <input type="text" id="search-bar" placeholder="카페를 검색해주세요" name="search" value="{{search}}">
          <input type="image" src="{% static 'search.png'%}" id="search-btn"></image>

        </div>
      </div>
    </form>
    <div class="cafe_card_wrapper">
      <div class="cafe_card_filter">
        <span>거리순 |</span>
        <span>관심순 |</span>

        <span>소식순</span>
      </div>
      {% for one_store in all_store %}

      <a href="{% url 'store_detail' one_store.id%}">
        <div class="cafe_card_img">
          <img src='{{one_store.image.url}}'>
        </div>
        <div class="cafe_card_content_wrap">
          <!-- 카페 스토리 : 일단 보류 -->
          <!-- <div class="cafe_card_story">
            <img src='{{one_store.story}}'>
          </div> -->

          <div class="cafe_card_content">
            <div class="cafe_card_title">{{one_store}}</div>
            <div class="cafe_card_loc">📌{{one_store.address}}<br>
            </div>

            <div class="cafe_card_time">⏰{{one_store.open_time}}<br>
            </div>
          </div>

          <div class="cafe_card_like">
            <a id="like_toggle" href="{% url 'like_toggle' one_store.id %}">
              {% if one_store in user.likes.all %}
              ♥ {{one_store.like_count}}
              {% else %}
              ♡ {{one_store.like_count}}
              {% endif %}
            </a>
          </div>

        </div>
      </a>
      {%endfor%}
    </div>

  </div>

</body>

</html>

Caffein/store/templates/store_update.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/cafe.css' %}">
    <link rel="stylesheet" href="{% static 'css/cafe_update.css' %}" />
  </head>
  <body>
    
    <form method="post">
        {% csrf_token %}
        <div class="container cafe-list">
          <h3>카페 정보 변경하기</h3>
          <input type="submit" value="Update" id="submit-btn">
          <hr>
        {% for i in form %}
        {%if i.name == "image" %}
        <div class="label-text">이미지 변경하기</div>
        {%elif i.name == "name" %}
        <div class="label-text">카페 이름</div>
        {%elif i.name == "address" %}
        <div class="label-text">
          <div class="detail_info_icon">
            <img class="icon-image" src="/static/지도 하양.png" >
            </div>카페 주소
        </div>
        {%elif i.name == "open_time" %}
        <div class="label-text">  
          <div class="detail_info_icon">
          <img class="icon-image" src="/static/메뉴 하양.png" >
        </div>
        영업 시간</div>
        {%elif i.name == "Info" %}
        <div class="label-text"> 
          <div class="detail_info_icon">
          <img class="icon-image" src="/static/메뉴판 하양.png" >
        </div>
        사장님의 한마디!</div>
        {%elif i.name == "more_info" %}
        <div class="label-text">
          <div class="detail_info_icon">
            <img class="icon-image-mark" src="/static/북마크 하양.png" >
          </div>
          추가 정보</div>
        {% endif %}
        <div class="label-input">{{i}}</div>
  
       
       
        {% endfor %}
      
    </div>
    </form>

       
    </body>
</html>